In [9]:
import numpy as np
import scipy.stats as sts
import matplotlib.pyplot as plt

In [22]:
sample_sizes = np.array([1000, 750, 500, 250, 100])
percentages = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [23]:
errs = np.empty([len(percentages), len(sample_sizes)])
for i in range(len(percentages)):
    mean = sample_sizes * percentages[i]
    std = np.sqrt(sample_sizes * percentages[i] * (1 - percentages[i]))
    sample_std = std / np.sqrt(sample_sizes)
    errs[i] = 1.96 * (sample_std / np.sqrt(sample_sizes))

In [24]:
print(np.around(errs, decimals=2))

[[0.02 0.02 0.03 0.04 0.06]
 [0.02 0.03 0.04 0.05 0.08]
 [0.03 0.03 0.04 0.06 0.09]
 [0.03 0.04 0.04 0.06 0.1 ]
 [0.03 0.04 0.04 0.06 0.1 ]
 [0.03 0.04 0.04 0.06 0.1 ]
 [0.03 0.03 0.04 0.06 0.09]
 [0.02 0.03 0.04 0.05 0.08]
 [0.02 0.02 0.03 0.04 0.06]]


Differences could be due to non-sample size error calculations, for example, non-response error when people don't pick up the phone, so that breaks complete randomization and makes the sample less representative. On the other hand, people who are on landlines are usually old people, so there is some re-scaling to balance population in terms of age.